### ISSUE TITLE
Refreshing problems

### ISSUE THREAD

**Issue by Azathoth88** [Maker-Management-Platform/mmp-companion#1]
There seems to be a refresh problem. After I created a test project and clicked on "Projects", it was not displayed. The same problem exists when I rename a project.

Only a complete browser refresh (F5) has updated the display.

Edit: I think I slipped with the message in the repository.

**Comment by EduardoOliveira** [comment]
Hello
That is indeed a problem, I would kindly ask you to recreate this ticket in https://github.com/Maker-Management-Platform/mmp-ui as that's the UI project
